
- name: Install Jenkins, Docker, Ansible, and Terraform
  hosts: nodes
  become: yes
  roles:
    - install_dependencies
    - configure_docker
    - configure_jenkins
    - configure_terraform
    - install_ansible
    - install_jenkins
    - install_docker
    - install_terraform

