---
# tasks file for install_jenkins
- name: Update apt cache with Jenkins and HashiCorp repositories
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  notify: "Start Jenkins service"
  when: ansible_os_family == "Debian"